manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: intheworks
      url-base: https://github.com/InTheWorks-ca/zmk.git
  projects:
    - name: zmk
      remote: intheworks
      revision: intheworks-test
      import: app/west.yml
  self:
    path: config
