manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: intheworks
      url-base: https://github.com/InTheWorks-ca
  projects:
    - name: zmk
#      remote: intheworks
#      revision: intheworks-test
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
